### PR TITLE
Add support for resizing-type=force

### PR DESCRIPTION
**Pull request by spantaleev**
As documented here: https://docs.imgproxy.net/generating_the_url?id=resizing-type

> force: resizes the image without keeping aspect ratio

### CODE REVIEW

**Comment by crocodile2u** [comment]
Great job, thank you. I will also add a new item to the test data provider `OptionSetTest::providerResizingType()`, then I will merge. You can also update your PR yourself, that'd be appreciated!

**Comment by spantaleev** [comment]
Updated the PR. Hope it's all good now!

**Comment by crocodile2u** [comment]
Yes, perfect! Great job!

**Comment by crocodile2u** [comment]
Enjoy: https://github.com/crocodile2u/imgproxy-php/releases/tag/v2.0.2

**Pull request merged**
